/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Backend.Cliente;
import Backend.DetallePedido;
import Backend.Empleado;
import Backend.Inventario;
import Backend.Libro;
import Backend.Notificacion;
import Backend.NotificacionEmail;
import Backend.NotificacionSMS;
import Backend.Venta;

/**
 *
 * @author carlo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Incialización de Inventario (Stock, Prestamos) Inicialización de ventas
     */
    private ArrayList<Libro> stock = new ArrayList<>();
    private ArrayList<Libro> prestamos = new ArrayList<>();
    private ArrayList<Cliente> clientes = new ArrayList<>();
    private Inventario inventario = new Inventario(stock, prestamos);
    int cp1 = 0;
    int cp2 = 1;

    private ArrayList<Venta> ventas = new ArrayList<Venta>();

    /**
     * Creates new form main
     */
    public void setPages() {
        if (stock.size() < 2) {
            if (stock.size() == 1) {
                lblBook1Info.setText("<html>Titulo: " + stock.get(cp1).getTitulo() + "<br>Autor: " + stock.get(cp1).getAutor() + " <br>ISBN: " + stock.get(cp1).getIsbn() + "<br>Precio: " + stock.get(cp1).getPrecio() + "<br>Disponibles: " + stock.get(cp1).getDisponibles() + "</html>");
                lblBook2Info.setText("<html>Titulo: No info <br>Autor: <br>ISBN: <br>Precio: <br>Disponibles: </html>");
            } else {
                lblBook1Info.setText("<html>Titulo: No info <br>Autor: <br>ISBN: <br>Precio: <br>Disponibles: </html>");
                lblBook2Info.setText("<html>Titulo: No info <br>Autor: <br>ISBN: <br>Precio: <br>Disponibles: </html>");
            }
        } else {
            lblBook1Info.setText("<html>Titulo: " + stock.get(cp1).getTitulo() + "<br>Autor: " + stock.get(cp1).getAutor() + " <br>ISBN: " + stock.get(cp1).getIsbn() + "<br>Precio: " + stock.get(cp1).getPrecio() + "<br>Disponibles: " + stock.get(cp1).getDisponibles() + "</html>");
            lblBook2Info.setText("<html>Titulo: " + stock.get(cp2).getTitulo() + "<br>Autor: " + stock.get(cp2).getAutor() + " <br>ISBN: " + stock.get(cp2).getIsbn() + "<br>Precio: " + stock.get(cp2).getPrecio() + "<br>Disponibles: " + stock.get(cp2).getDisponibles() + "</html>");
        }
    }

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intFrameAdminVentas = new javax.swing.JInternalFrame();
        backgroundAdminPrestamos1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ventasTable = new javax.swing.JTable();
        btnDetallesVenta = new javax.swing.JButton();
        intFrameAdminPrestamos = new javax.swing.JInternalFrame();
        backgroundAdminPrestamos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        prestamosTable = new javax.swing.JTable();
        btnEliminarPrestamo = new javax.swing.JButton();
        intFrameAdminInventario = new javax.swing.JInternalFrame();
        backgroundAdminInventario = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventarioTable = new javax.swing.JTable();
        btnAgregarStock = new javax.swing.JButton();
        btnEliminarStock = new javax.swing.JButton();
        intFrameCliente = new javax.swing.JInternalFrame();
        backgroundCliente = new javax.swing.JPanel();
        panelBookClient = new javax.swing.JPanel();
        lblBookClientInfo = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();
        intFrameAdminConfig = new javax.swing.JInternalFrame();
        backgroundAdminConfig = new javax.swing.JPanel();
        btnAdminVentas = new javax.swing.JButton();
        btnAdminInventario = new javax.swing.JButton();
        btnAdminPrestamos = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        lblMainLogo = new javax.swing.JLabel();
        panelBook1 = new javax.swing.JPanel();
        lblBook1Info = new javax.swing.JLabel();
        panelBook2 = new javax.swing.JPanel();
        lblBook2Info = new javax.swing.JLabel();
        lblBookInfoHolder = new javax.swing.JLabel();
        btnPreviousBook = new javax.swing.JButton();
        btnNextBook = new javax.swing.JButton();
        btnAdminConfig = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lectura sin fin");
        setMinimumSize(new java.awt.Dimension(1344, 756));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        intFrameAdminVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        intFrameAdminVentas.setClosable(true);
        intFrameAdminVentas.setTitle("Ventas");
        intFrameAdminVentas.setMaximumSize(new java.awt.Dimension(700, 450));
        intFrameAdminVentas.setMinimumSize(new java.awt.Dimension(700, 450));
        intFrameAdminVentas.setPreferredSize(new java.awt.Dimension(700, 450));
        intFrameAdminVentas.setVisible(false);
        intFrameAdminVentas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundAdminPrestamos1.setBackground(new java.awt.Color(255, 189, 89));
        backgroundAdminPrestamos1.setMaximumSize(new java.awt.Dimension(700, 430));
        backgroundAdminPrestamos1.setMinimumSize(new java.awt.Dimension(700, 430));
        backgroundAdminPrestamos1.setPreferredSize(new java.awt.Dimension(700, 430));
        backgroundAdminPrestamos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setFocusable(false);
        jScrollPane4.setMaximumSize(new java.awt.Dimension(500, 250));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(500, 250));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(500, 250));

        ventasTable.setBackground(new java.awt.Color(255, 247, 177));
        ventasTable.setForeground(new java.awt.Color(73, 66, 60));
        ventasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Comprador", "ID Vendedor", "Libro", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ventasTable.setGridColor(new java.awt.Color(255, 247, 177));
        ventasTable.setSelectionBackground(new java.awt.Color(132, 79, 79));
        ventasTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ventasTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ventasTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ventasTable.setShowGrid(true);
        jScrollPane4.setViewportView(ventasTable);

        backgroundAdminPrestamos1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 500, 250));

        btnDetallesVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnDetalles.png"))); // NOI18N
        btnDetallesVenta.setFocusable(false);
        btnDetallesVenta.setMaximumSize(new java.awt.Dimension(140, 50));
        btnDetallesVenta.setMinimumSize(new java.awt.Dimension(140, 50));
        btnDetallesVenta.setPreferredSize(new java.awt.Dimension(75, 25));
        btnDetallesVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesVentaActionPerformed(evt);
            }
        });
        backgroundAdminPrestamos1.add(btnDetallesVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 310, 210, 80));

        intFrameAdminVentas.getContentPane().add(backgroundAdminPrestamos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        getContentPane().add(intFrameAdminVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 155, 700, 450));

        intFrameAdminPrestamos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        intFrameAdminPrestamos.setClosable(true);
        intFrameAdminPrestamos.setTitle("Prestamos");
        intFrameAdminPrestamos.setMaximumSize(new java.awt.Dimension(700, 450));
        intFrameAdminPrestamos.setMinimumSize(new java.awt.Dimension(700, 450));
        intFrameAdminPrestamos.setPreferredSize(new java.awt.Dimension(700, 450));
        intFrameAdminPrestamos.setVisible(false);
        intFrameAdminPrestamos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundAdminPrestamos.setBackground(new java.awt.Color(255, 189, 89));
        backgroundAdminPrestamos.setMaximumSize(new java.awt.Dimension(700, 430));
        backgroundAdminPrestamos.setMinimumSize(new java.awt.Dimension(700, 430));
        backgroundAdminPrestamos.setPreferredSize(new java.awt.Dimension(700, 430));
        backgroundAdminPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setFocusable(false);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(500, 250));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(500, 250));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(500, 250));

        prestamosTable.setBackground(new java.awt.Color(255, 247, 177));
        prestamosTable.setForeground(new java.awt.Color(73, 66, 60));
        prestamosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Nombre Cliente", "Titulo", "Autor", "ISBN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prestamosTable.setGridColor(new java.awt.Color(255, 247, 177));
        prestamosTable.setSelectionBackground(new java.awt.Color(132, 79, 79));
        prestamosTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        prestamosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prestamosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prestamosTable.setShowGrid(true);
        jScrollPane3.setViewportView(prestamosTable);

        backgroundAdminPrestamos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 500, 250));

        btnEliminarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnEliminar.png"))); // NOI18N
        btnEliminarPrestamo.setFocusable(false);
        btnEliminarPrestamo.setMaximumSize(new java.awt.Dimension(140, 50));
        btnEliminarPrestamo.setMinimumSize(new java.awt.Dimension(140, 50));
        btnEliminarPrestamo.setPreferredSize(new java.awt.Dimension(140, 50));
        btnEliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPrestamoActionPerformed(evt);
            }
        });
        backgroundAdminPrestamos.add(btnEliminarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 210, 80));

        intFrameAdminPrestamos.getContentPane().add(backgroundAdminPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        getContentPane().add(intFrameAdminPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 155, 700, 450));

        intFrameAdminInventario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        intFrameAdminInventario.setClosable(true);
        intFrameAdminInventario.setTitle("Inventario");
        intFrameAdminInventario.setMaximumSize(new java.awt.Dimension(700, 450));
        intFrameAdminInventario.setMinimumSize(new java.awt.Dimension(700, 450));
        intFrameAdminInventario.setPreferredSize(new java.awt.Dimension(700, 450));
        intFrameAdminInventario.setVisible(false);
        intFrameAdminInventario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundAdminInventario.setBackground(new java.awt.Color(255, 189, 89));
        backgroundAdminInventario.setMaximumSize(new java.awt.Dimension(700, 430));
        backgroundAdminInventario.setMinimumSize(new java.awt.Dimension(700, 430));
        backgroundAdminInventario.setPreferredSize(new java.awt.Dimension(700, 430));
        backgroundAdminInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(132, 79, 79));
        jScrollPane2.setFocusable(false);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(500, 250));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(500, 250));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 250));

        inventarioTable.setBackground(new java.awt.Color(255, 247, 177));
        inventarioTable.setForeground(new java.awt.Color(73, 66, 60));
        inventarioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "ISBN", "Precio", "Disponibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventarioTable.setGridColor(new java.awt.Color(255, 247, 177));
        inventarioTable.setSelectionBackground(new java.awt.Color(132, 79, 79));
        inventarioTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        inventarioTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        inventarioTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        inventarioTable.setShowGrid(true);
        jScrollPane2.setViewportView(inventarioTable);

        backgroundAdminInventario.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 500, 250));

        btnAgregarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnAgregar.png"))); // NOI18N
        btnAgregarStock.setFocusable(false);
        btnAgregarStock.setMaximumSize(new java.awt.Dimension(140, 50));
        btnAgregarStock.setMinimumSize(new java.awt.Dimension(140, 50));
        btnAgregarStock.setPreferredSize(new java.awt.Dimension(75, 25));
        btnAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockActionPerformed(evt);
            }
        });
        backgroundAdminInventario.add(btnAgregarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 210, 80));

        btnEliminarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnEliminar.png"))); // NOI18N
        btnEliminarStock.setFocusable(false);
        btnEliminarStock.setMaximumSize(new java.awt.Dimension(140, 50));
        btnEliminarStock.setMinimumSize(new java.awt.Dimension(140, 50));
        btnEliminarStock.setPreferredSize(new java.awt.Dimension(140, 50));
        btnEliminarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarStockActionPerformed(evt);
            }
        });
        backgroundAdminInventario.add(btnEliminarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 210, 80));

        intFrameAdminInventario.getContentPane().add(backgroundAdminInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        getContentPane().add(intFrameAdminInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 155, 700, 450));

        intFrameCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        intFrameCliente.setClosable(true);
        intFrameCliente.setTitle("Cliente");
        intFrameCliente.setMaximumSize(new java.awt.Dimension(700, 450));
        intFrameCliente.setMinimumSize(new java.awt.Dimension(700, 450));
        intFrameCliente.setPreferredSize(new java.awt.Dimension(700, 450));
        intFrameCliente.setVisible(false);
        intFrameCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundCliente.setBackground(new java.awt.Color(255, 189, 89));
        backgroundCliente.setFocusable(false);
        backgroundCliente.setMaximumSize(new java.awt.Dimension(700, 430));
        backgroundCliente.setMinimumSize(new java.awt.Dimension(700, 430));
        backgroundCliente.setPreferredSize(new java.awt.Dimension(700, 430));
        backgroundCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBookClient.setBackground(new java.awt.Color(132, 79, 79));
        panelBookClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panelBookClient.setMaximumSize(new java.awt.Dimension(210, 300));
        panelBookClient.setPreferredSize(new java.awt.Dimension(210, 300));
        panelBookClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBookClientInfo.setBackground(new java.awt.Color(73, 66, 60));
        lblBookClientInfo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblBookClientInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblBookClientInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookClientInfo.setText("<html>Titulo: No info<br>Autor: <br>ISBN: <br>Precio: <br>Disponibles: </html>");
        lblBookClientInfo.setAlignmentY(5.0F);
        lblBookClientInfo.setMaximumSize(new java.awt.Dimension(200, 300));
        lblBookClientInfo.setMinimumSize(new java.awt.Dimension(200, 300));
        lblBookClientInfo.setPreferredSize(new java.awt.Dimension(200, 300));
        panelBookClient.add(lblBookClientInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 300));

        backgroundCliente.add(panelBookClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 210, 300));

        btnComprar.setBackground(new java.awt.Color(132, 79, 79));
        btnComprar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnComprar.png"))); // NOI18N
        btnComprar.setBorder(null);
        btnComprar.setFocusable(false);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        backgroundCliente.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 210, 80));

        btnPrestar.setBackground(new java.awt.Color(132, 79, 79));
        btnPrestar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        btnPrestar.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnPrestar.png"))); // NOI18N
        btnPrestar.setBorder(null);
        btnPrestar.setFocusable(false);
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });
        backgroundCliente.add(btnPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 210, 80));

        intFrameCliente.getContentPane().add(backgroundCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        getContentPane().add(intFrameCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 155, 700, 450));

        intFrameAdminConfig.setBackground(new java.awt.Color(255, 247, 177));
        intFrameAdminConfig.setBorder(null);
        intFrameAdminConfig.setClosable(true);
        intFrameAdminConfig.setTitle("Administrador");
        intFrameAdminConfig.setMaximumSize(new java.awt.Dimension(700, 450));
        intFrameAdminConfig.setMinimumSize(new java.awt.Dimension(700, 450));
        intFrameAdminConfig.setPreferredSize(new java.awt.Dimension(700, 450));
        try {
            intFrameAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        intFrameAdminConfig.setVisible(false);
        intFrameAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundAdminConfig.setBackground(new java.awt.Color(255, 189, 89));
        backgroundAdminConfig.setFocusable(false);
        backgroundAdminConfig.setMaximumSize(new java.awt.Dimension(700, 430));
        backgroundAdminConfig.setMinimumSize(new java.awt.Dimension(700, 430));
        backgroundAdminConfig.setPreferredSize(new java.awt.Dimension(700, 430));
        backgroundAdminConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnVentas.png"))); // NOI18N
        btnAdminVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAdminVentas.setFocusable(false);
        btnAdminVentas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminVentas.setMaximumSize(new java.awt.Dimension(180, 300));
        btnAdminVentas.setMinimumSize(new java.awt.Dimension(180, 300));
        btnAdminVentas.setPreferredSize(new java.awt.Dimension(180, 300));
        btnAdminVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminVentasActionPerformed(evt);
            }
        });
        backgroundAdminConfig.add(btnAdminVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, 300));

        btnAdminInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnInventario.png"))); // NOI18N
        btnAdminInventario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAdminInventario.setFocusable(false);
        btnAdminInventario.setMaximumSize(new java.awt.Dimension(180, 300));
        btnAdminInventario.setMinimumSize(new java.awt.Dimension(180, 300));
        btnAdminInventario.setPreferredSize(new java.awt.Dimension(180, 300));
        btnAdminInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInventarioActionPerformed(evt);
            }
        });
        backgroundAdminConfig.add(btnAdminInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 180, 300));

        btnAdminPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnPrestamos.png"))); // NOI18N
        btnAdminPrestamos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAdminPrestamos.setFocusable(false);
        btnAdminPrestamos.setMaximumSize(new java.awt.Dimension(180, 300));
        btnAdminPrestamos.setMinimumSize(new java.awt.Dimension(180, 300));
        btnAdminPrestamos.setPreferredSize(new java.awt.Dimension(180, 300));
        btnAdminPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminPrestamosActionPerformed(evt);
            }
        });
        backgroundAdminConfig.add(btnAdminPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 180, 300));

        intFrameAdminConfig.getContentPane().add(backgroundAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        getContentPane().add(intFrameAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 155, 700, 450));

        background.setBackground(new java.awt.Color(255, 247, 177));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/lecturaSinFinLogo.png"))); // NOI18N
        background.add(lblMainLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 30, 120, 120));

        panelBook1.setBackground(new java.awt.Color(255, 255, 255));
        panelBook1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panelBook1.setMaximumSize(new java.awt.Dimension(210, 300));
        panelBook1.setPreferredSize(new java.awt.Dimension(210, 300));
        panelBook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBook1MouseClicked(evt);
            }
        });
        panelBook1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBook1Info.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblBook1Info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBook1Info.setText("<html>Titulo: No info<br>Autor: <br>ISBN: <br>Precio: <br>Disponibles: </html>");
        lblBook1Info.setAlignmentY(5.0F);
        lblBook1Info.setMaximumSize(new java.awt.Dimension(200, 300));
        lblBook1Info.setMinimumSize(new java.awt.Dimension(200, 300));
        lblBook1Info.setPreferredSize(new java.awt.Dimension(200, 300));
        panelBook1.add(lblBook1Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 300));

        background.add(panelBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 210, 300));

        panelBook2.setBackground(new java.awt.Color(255, 255, 255));
        panelBook2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panelBook2.setMaximumSize(new java.awt.Dimension(210, 300));
        panelBook2.setPreferredSize(new java.awt.Dimension(210, 300));
        panelBook2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBook2MouseClicked(evt);
            }
        });
        panelBook2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBook2Info.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblBook2Info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBook2Info.setText("<html>Titulo: No info <br>Autor: <br>ISBN: <br>Precio: <br>Disponibles: </html>");
        lblBook2Info.setAlignmentY(5.0F);
        lblBook2Info.setMaximumSize(new java.awt.Dimension(200, 300));
        lblBook2Info.setMinimumSize(new java.awt.Dimension(200, 300));
        lblBook2Info.setPreferredSize(new java.awt.Dimension(200, 300));
        panelBook2.add(lblBook2Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 300));

        background.add(panelBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 210, 300));

        lblBookInfoHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/bookInfoHolder.png"))); // NOI18N
        background.add(lblBookInfoHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 180, 660, 420));

        btnPreviousBook.setBackground(new java.awt.Color(255, 189, 89));
        btnPreviousBook.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 40)); // NOI18N
        btnPreviousBook.setForeground(new java.awt.Color(73, 66, 60));
        btnPreviousBook.setText("<");
        btnPreviousBook.setBorder(null);
        btnPreviousBook.setFocusable(false);
        btnPreviousBook.setMaximumSize(new java.awt.Dimension(80, 230));
        btnPreviousBook.setMinimumSize(new java.awt.Dimension(80, 230));
        btnPreviousBook.setName(""); // NOI18N
        btnPreviousBook.setPreferredSize(new java.awt.Dimension(80, 230));
        btnPreviousBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousBookActionPerformed(evt);
            }
        });
        background.add(btnPreviousBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 300, 80, 230));

        btnNextBook.setBackground(new java.awt.Color(255, 189, 89));
        btnNextBook.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 40)); // NOI18N
        btnNextBook.setForeground(new java.awt.Color(73, 66, 60));
        btnNextBook.setText(">");
        btnNextBook.setBorder(null);
        btnNextBook.setFocusable(false);
        btnNextBook.setMaximumSize(new java.awt.Dimension(80, 230));
        btnNextBook.setMinimumSize(new java.awt.Dimension(80, 230));
        btnNextBook.setName(""); // NOI18N
        btnNextBook.setPreferredSize(new java.awt.Dimension(80, 230));
        btnNextBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextBookActionPerformed(evt);
            }
        });
        background.add(btnNextBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 300, 80, 230));

        btnAdminConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnAdmin.png"))); // NOI18N
        btnAdminConfig.setBorder(null);
        btnAdminConfig.setFocusable(false);
        btnAdminConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminConfigActionPerformed(evt);
            }
        });
        background.add(btnAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 620, 100, 100));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/btnSalir.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setFocusable(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        background.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 620, 100, 100));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1344, 756));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousBookActionPerformed
        if (cp1 < 0) {
            cp1 = 0;
            cp2 = 1;
            setPages();
        } else if (cp1 == 0 && cp2 == 1 && stock.size() >= 2) {
            cp2 = stock.size() - 1;
            cp1 = stock.size() - 2;
            setPages();
        } else if (cp1 == 1 && cp2 == 2) {
            cp1 = stock.size() - 1;
            cp2 = 0;
            setPages();
        } else if (cp1 == stock.size() - 1 && cp2 == 0) {
            cp1 = 2;
            cp2 = 3;
            setPages();
        } else if (cp1 <= stock.size() || cp2 <= stock.size() || stock.size() < 2){
            cp1 = 0;
            cp2 = 1;
            setPages();
        } else {
            cp1 -= 2;
            cp2 -= 2;
            setPages();
        }
    }//GEN-LAST:event_btnPreviousBookActionPerformed

    private void panelBook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBook1MouseClicked
        if (!inventario.getStock().isEmpty()){
            intFrameCliente.setVisible(!intFrameCliente.isVisible());
            lblBookClientInfo.setText(lblBook1Info.getText());
        }
    }//GEN-LAST:event_panelBook1MouseClicked

    private void btnAdminConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminConfigActionPerformed
        intFrameAdminConfig.setVisible(!intFrameAdminConfig.isVisible());
    }//GEN-LAST:event_btnAdminConfigActionPerformed

    private void btnAdminVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminVentasActionPerformed
        intFrameAdminVentas.setVisible(!intFrameAdminVentas.isVisible());
        writeVentasTable(ventasTable, ventas);
        intFrameAdminConfig.setVisible(false);
    }//GEN-LAST:event_btnAdminVentasActionPerformed

    public void writeLibroTable(javax.swing.JTable table, ArrayList<Libro> list) {
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn("Titulo");
        modelo.addColumn("Autor");
        modelo.addColumn("ISBN");
        modelo.addColumn("Precio");
        modelo.addColumn("Disponibles");
        table.setModel(modelo);
        for (Libro lb : list) {
            modelo.addRow(new Object[]{lb.getTitulo(), lb.getAutor(), lb.getIsbn(), lb.getPrecio(), lb.getDisponibles()});
        }
    }

    public void writeVentasTable(javax.swing.JTable table, ArrayList<Venta> list) {
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn("Cliente");
        modelo.addColumn("Gestor");
        modelo.addColumn("Libro");
        modelo.addColumn("Fecha");
        table.setModel(modelo);
        for (Venta v : list) {
            modelo.addRow(new Object[]{v.getPedido().getComprador().getId(), v.getPedido().getGestor().getId(), v.getLibro().getIsbn(), v.getFecha()});
        }
    }

    public void writePrestamosTable(javax.swing.JTable table, ArrayList<Cliente> list) {
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn("Id Cliente");
        modelo.addColumn("nombre Cliente");
        modelo.addColumn("Titulo");
        modelo.addColumn("Autor");
        modelo.addColumn("ISBN");
        modelo.addColumn("Precio");
        table.setModel(modelo);
        for (Cliente cli : list) {
            for (Libro lib : cli.getHistorialPrestamos()) {
                modelo.addRow(new Object[]{cli.getId(), cli.getNombre() + " " + cli.getApellido(), lib.getTitulo(), lib.getAutor(), lib.getIsbn(), lib.getPrecio()});
            }
        }
    }
    private void btnAdminInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInventarioActionPerformed
        intFrameAdminInventario.setVisible(!intFrameAdminInventario.isVisible());
        writeLibroTable(inventarioTable, inventario.getStock());
        intFrameAdminConfig.setVisible(false);
    }//GEN-LAST:event_btnAdminInventarioActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        Notificacion nf = new NotificacionSMS();
        try {
            int id = Integer.parseInt(JOptionPane.showInputDialog(null, "ID de cliente: ", "Cliente", 3));
            String name = JOptionPane.showInputDialog(null, "Nombre de cliente: ", "Cliente", 3);
            if (name != null && !name.isBlank()){
                
                String ap = JOptionPane.showInputDialog(null, "Apellido de cliente: ", "Cliente", 3); 
                if (ap != null && !ap.isBlank()){
                    Cliente cli = new Cliente(id,name,ap,new ArrayList<Libro>());
                
                    clientes.add(cli);
                    Libro lib = new Libro();
                    for (Libro l : stock) {
                        if (lblBookClientInfo.getText().contains("ISBN: " + l.getIsbn())) {
                            lib = l;
                        }
                    }
                    inventario.agregarAPrestamos(lib);
                    cli.getHistorialPrestamos().add(lib);
                    intFrameCliente.dispose();
                    setPages();
                    writePrestamosTable(prestamosTable, clientes);
                    nf.enviarMensaje("Prestamo registrado correctamente");
                } else {
                    nf.enviarMensaje("Se ha cancelado el prestamo");
                }
            } else {
                nf.enviarMensaje("Se ha cancelado el prestamo");
            }
            
        } catch (Exception e) {
            nf.enviarMensaje("Error al registrar el prestamo");
        }
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAdminPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminPrestamosActionPerformed
        intFrameAdminPrestamos.setVisible(!intFrameAdminPrestamos.isVisible());
        writePrestamosTable(prestamosTable, clientes);
        intFrameAdminConfig.setVisible(false);
    }//GEN-LAST:event_btnAdminPrestamosActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        Notificacion nf = new NotificacionEmail();
        try {
            Cliente cli = new Cliente(Integer.parseInt(JOptionPane.showInputDialog(null, "ID de cliente: ", "Cliente", 3)), JOptionPane.showInputDialog(null, "Nombre de cliente: ", "Cliente", 3), JOptionPane.showInputDialog(null, "Apellido de cliente: ", "Cliente", 3), new ArrayList<Libro>());
            Empleado emp = new Empleado(Integer.parseInt(JOptionPane.showInputDialog(null, "ID de gestor: ", "Gestor", 3)), JOptionPane.showInputDialog(null, "Nombre de gestor: ", "Gestor", 3), JOptionPane.showInputDialog(null, "Apellido de gestor: ", "Gestor", 3), "gestor");
            Libro lib = new Libro();
            for (Libro l : stock) {
                if (lblBookClientInfo.getText().contains("ISBN: " + l.getIsbn())) {
                    lib = l;
                }
            }
            Venta ven = new Venta(cli, emp, new ArrayList<DetallePedido>(), lib);
            ventas.add(ven);
            inventario.eliminarDeStock(lib);
            intFrameCliente.dispose();
            setPages();
            writeVentasTable(ventasTable, ventas);
            nf.enviarMensaje("Venta registrada correctamente");
        } catch (Exception e) {
            nf.enviarMensaje("Error al registrar la venta");
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnDetallesVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesVentaActionPerformed
        for (int i = 0; i < ventas.size(); i++) {
            if (ventas.get(i).getPedido().getComprador().getId() == (int) ventasTable.getModel().getValueAt(ventasTable.getSelectedRow(), 0) && ventas.get(i).getPedido().getGestor().getId() == (int) ventasTable.getModel().getValueAt(ventasTable.getSelectedRow(), 1) && ventas.get(i).getLibro().getIsbn() == (long)(ventasTable.getModel().getValueAt(ventasTable.getSelectedRow(), 2))) {
                int sz = ventas.get(i).getPedido().getDetalles().size();
                for (int j = 0; j < sz; j++) {
                    JOptionPane.showMessageDialog(null, ventas.get(i).getPedido().getDetalles().get(j).getDetalle(), "Detalle de pedido #" + (j + 1), 1);
                }
            }
        }
    }//GEN-LAST:event_btnDetallesVentaActionPerformed

    private void btnNextBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextBookActionPerformed
        if (cp1 >= stock.size() || cp2 >= stock.size()) {
            cp1 = 0;
            cp2 = 1;
            setPages();
        } else if (cp1 == stock.size() - 3) {
            cp1 += 2;
            cp2 = 0;
            setPages();
        } else if (cp1 == stock.size() - 2 && cp2 == stock.size() - 1) {
            cp1 = 0;
            cp2 = 1;
            setPages();
        } else {
            cp1 = cp2 + 1;
            cp2 += 2;
            setPages();
        }
    }//GEN-LAST:event_btnNextBookActionPerformed

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
        try {
            Libro lb = new Libro(JOptionPane.showInputDialog(null, "Titulo del libro: ", "Libro", 3), JOptionPane.showInputDialog(null, "Nombre del autor: ", "Libro", 3), Long.parseLong(JOptionPane.showInputDialog(null, "ISBN: ", "Libro", 3)), Double.parseDouble(JOptionPane.showInputDialog(null, "Precio: ", "Libro", 3)), Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de disponibles: ", "Libro", 3)));
            if (lb.getDisponibles() >= 0 && lb.getPrecio() >= 0 && lb.getIsbn() >= 0 && !lb.getAutor().isBlank() && !lb.getTitulo().isBlank()){
                inventario.agregarAStock(lb);
            
                writeLibroTable(inventarioTable, inventario.getStock());
                JOptionPane.showMessageDialog(null, "Libro registrado correctamente", "Libro", 1);
                setPages();
                intFrameAdminInventario.setVisible(false);
                intFrameAdminInventario.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Error, uno de los campos no es valido", "Libro", 0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al registrar el libro", "Libro", 0);
        }

    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void btnEliminarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarStockActionPerformed
        try {
            inventario.getStock().remove(inventarioTable.getSelectedRow());
            writeLibroTable(inventarioTable, inventario.getStock());
            JOptionPane.showMessageDialog(null, "Libro eliminado correctamente", "Libro", 1);
            setPages();
            intFrameAdminInventario.setVisible(false);
            intFrameAdminInventario.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el libro", "Libro", 0);
        }

    }//GEN-LAST:event_btnEliminarStockActionPerformed

    private void panelBook2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBook2MouseClicked
        if (inventario.getStock().size() > 1){
            intFrameCliente.setVisible(!intFrameCliente.isVisible());
            lblBookClientInfo.setText(lblBook2Info.getText());
        }
    }//GEN-LAST:event_panelBook2MouseClicked

    private void btnEliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoActionPerformed
        if (prestamosTable.getSelectedRow() != -1){
            inventario.getPrestamos().remove(prestamosTable.getSelectedRow());
            int id = (int) prestamosTable.getModel().getValueAt(prestamosTable.getSelectedRow(), 0);
            long isbn = (long) prestamosTable.getModel().getValueAt(prestamosTable.getSelectedRow(), 4);
            for (int i = 0; i < clientes.size(); i++) {
                for (int j = 0; j < clientes.get(i).getHistorialPrestamos().size(); j++) {
                    if (clientes.get(i).getId() == id && clientes.get(i).getHistorialPrestamos().get(j).getIsbn() == isbn) {
                        clientes.get(i).getHistorialPrestamos().remove(j);
                        break;
                    }
                }
            }
            writePrestamosTable(prestamosTable, clientes);
        }
    }//GEN-LAST:event_btnEliminarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JFrame SS = new SplashScreen();
        SS.setLocationRelativeTo(null);
        SS.setVisible(true);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            System.out.println("Chale Mi casita");
        }
        SS.dispose();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame mainForm = new Main();
                mainForm.setLocationRelativeTo(null);

                mainForm.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundAdminConfig;
    private javax.swing.JPanel backgroundAdminInventario;
    private javax.swing.JPanel backgroundAdminPrestamos;
    private javax.swing.JPanel backgroundAdminPrestamos1;
    private javax.swing.JPanel backgroundCliente;
    private javax.swing.JButton btnAdminConfig;
    private javax.swing.JButton btnAdminInventario;
    private javax.swing.JButton btnAdminPrestamos;
    private javax.swing.JButton btnAdminVentas;
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnDetallesVenta;
    private javax.swing.JButton btnEliminarPrestamo;
    private javax.swing.JButton btnEliminarStock;
    private javax.swing.JButton btnNextBook;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnPreviousBook;
    private javax.swing.JInternalFrame intFrameAdminConfig;
    private javax.swing.JInternalFrame intFrameAdminInventario;
    private javax.swing.JInternalFrame intFrameAdminPrestamos;
    private javax.swing.JInternalFrame intFrameAdminVentas;
    private javax.swing.JInternalFrame intFrameCliente;
    private javax.swing.JTable inventarioTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBook1Info;
    private javax.swing.JLabel lblBook2Info;
    private javax.swing.JLabel lblBookClientInfo;
    private javax.swing.JLabel lblBookInfoHolder;
    private javax.swing.JLabel lblMainLogo;
    private javax.swing.JPanel panelBook1;
    private javax.swing.JPanel panelBook2;
    private javax.swing.JPanel panelBookClient;
    private javax.swing.JTable prestamosTable;
    private javax.swing.JTable ventasTable;
    // End of variables declaration//GEN-END:variables
}
