/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

/**
 *
 * @author carlo
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblMainLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblBookInfoHolder = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lectura sin fin");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1344, 756));
        setMinimumSize(new java.awt.Dimension(1344, 756));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 247, 177));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/lecturaSinFinLogo.png"))); // NOI18N
        background.add(lblMainLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 30, 120, 120));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setMaximumSize(new java.awt.Dimension(210, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(210, 300));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html>Titulo: XXXXXXXXXX <br>Autor: XXXXXXXXXX <br>ISBN: XXXXXXXXX <br>Precio: XXXXXXXXXX <br>Disponibles: XXX</html>");
        jLabel1.setAlignmentY(5.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 300));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 300));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 300));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 210, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(210, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(210, 300));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html>Titulo: XXXXXXXXXX <br>Autor: XXXXXXXXXX <br>ISBN: XXXXXXXXX <br>Precio: XXXXXXXXXX <br>Disponibles: XXX</html>");
        jLabel2.setAlignmentY(5.0F);
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 300));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 300));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 300));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 300));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 210, 300));

        lblBookInfoHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/media/bookInfoHolder.png"))); // NOI18N
        background.add(lblBookInfoHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 180, 660, 420));

        jButton1.setBackground(new java.awt.Color(255, 189, 89));
        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 40)); // NOI18N
        jButton1.setText("<");
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.setMaximumSize(new java.awt.Dimension(80, 230));
        jButton1.setMinimumSize(new java.awt.Dimension(80, 230));
        jButton1.setName(""); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(80, 230));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 300, 80, 230));

        jButton2.setBackground(new java.awt.Color(255, 189, 89));
        jButton2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 40)); // NOI18N
        jButton2.setText(">");
        jButton2.setBorder(null);
        jButton2.setFocusable(false);
        jButton2.setMaximumSize(new java.awt.Dimension(80, 230));
        jButton2.setMinimumSize(new java.awt.Dimension(80, 230));
        jButton2.setName(""); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(80, 230));
        background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 300, 80, 230));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1344, 756));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        System.out.println("Presionaste el panel 1");
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        System.out.println("Presionaste el panel 2");
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBookInfoHolder;
    private javax.swing.JLabel lblMainLogo;
    // End of variables declaration//GEN-END:variables
}
